### ISSUE TITLE
Provided X-Login, X-Username

### ISSUE THREAD

**Issue by HeineDeelstra** [ThijsFeryn/cacheable-site-silex#2]
I came here from your blog on JWT sessions & Varnish. 

In the example v2, I wonder what would happen if the user would supply no token, but their own X-Login and X-Username headers. Shouldn't all those internal headers be unconditionally unset at the start of sub jwt or even the vcl?

**Comment by ThijsFeryn** [comment]
Hi @HeineDeelstra, thanks for the feedback. I'd say you're 100% correct, and I'll fix the issue ASAP.

Fix coming soon.

**Comment by ThijsFeryn** [comment]
Fixed in 67206c8dfd37ac781b51a1d2b75fe1e9b762bcce
